imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine.yml }
    - { resource: fos_oauth_server.yml }
#    - { resource: cache.php }
    - { resource: jwt.php }
    - { resource: doctrine_extensions.yml }

parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_rest:
    view:
        view_response_listener: 'true'
    routing_loader:
        include_format: true
        default_format: json
    param_fetcher_listener: true

jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT
    metadata:
        auto_detection: true
        directories:
            OAuthServerBundle:
                namespace_prefix: "FOS\\OAuthServerBundle"
                path: "@AppBundle/Resources/config/serializer"
            AppBundle:
                namespace_prefix: "AppBundle\\Entity"
                path: "@AppBundle/Resources/config/serializer"


#lsw_memcache:
#    pools:
#        default:
#            servers: %memcached_servers%
#    session:
#        pool: default
#        prefix: %kernel.cache_dir%

hwi_oauth:
    firewall_names: [main]
    resource_owners:
        any_name:
            type: facebook
            client_id: 1571148386532175
            client_secret: e92676a8cc39ad5da3eb2c7a820ba1a

parameters:
    twig.controller.exception.class: AppBundle\Controller\ExceptionController
    twig.exception_listener.class: AppBundle\Exception\Listener\ExceptionListener