# Doctrine Configuration
doctrine:
    dbal:
        default_connection: auth
        connections:
            auth:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                server_version: 5.6

    orm:
        default_entity_manager: auth
        entity_managers:
            auth:
                auto_mapping: true
                connection: auth
        auto_generate_proxy_classes: "%kernel.debug%"
