fos_oauth_server:
    db_driver:           orm
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode
    service:
        user_provider: app_bundle.security.user.provider
        options:
            access_token_lifetime:  43200
            refresh_token_lifetime: 1209600
            id_token_lifetime:      43200
            supported_scopes:       default