hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

manager:
    resource: "@AuthManagerBundle/Resources/config/routing.yml"
    prefix: /
