security:
    providers:
        default:
            id: security.user.provider
    encoders:
        bcrypt:
            algorithm:        bcrypt
            cost:             13
        main:
            id:               main.security.encoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false
        oauth_token_introspection:
            pattern:    ^/oauth/v2/introspection
            fos_oauth:  true
            stateless:  true
            anonymous:  false
        api_doc:
            pattern:    ^/api/doc
            fos_oauth:  false
            stateless:  true
            anonymous:  true
        api:
            pattern:    ^/api
            fos_oauth: true
            stateless:  true
            anonymous:  false
        main:
            pattern: ^/
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider

    access_control:
        - { path: ^/api/doc, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/oauth/v2/introspection, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
